const getColumns = () => {

    return [
        {
            id: "checkbox",
            visible: true,
            pinned: true,
            width: "54px",
        },
        {
            id: "2",
            field: "Key",
            label: "Key",
            visible: true,
            searchable: true,
            editable: true,
            sortable: true,
            resizable: true,
        },
        {
            id: "3",
            field: "Category",
            label: "Category",
            visible: true,
            searchable: true,
            editable: true,
            sortable: true,
            resizable: true,
        },
        {
            id: "4",
            field: "DefinitionType",
            label: "Definition Type",
            visible: true,
            searchable: true,
            editable: true,
            sortable: true,
            resizable: true,
        },
        {
            id: "5",
            field: "Module",
            label: "Module",
            visible: true,
            searchable: true,
            editable: true,
            sortable: true,
            resizable: true,
        },
        {
            id: "6",
            field: "Profile",
            label: "Profile",
            visible: true,
            searchable: true,
            editable: true,
            sortable: true,
            resizable: true,
        },
        {
            id: "8",
            field: "Retailer",
            label: "Retailer",
            visible: true,
            searchable: true,
            editable: true,
            sortable: true,
            resizable: true,
        },
        {
            id: "9",
            field: "DefaultValue",
            label: "Default value",
            visible: true,
            searchable: true,
            editable: true,
            sortable: true,
            resizable: true,
        },
    ];
};

export default getColumns;
